name: CI

on:
  workflow_dispatch:

jobs:
  build-kernel:
    name: Build Kernel
    runs-on: ubuntu-20.04
    steps:
      - name: Build
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/chiteroman/kernel_vayu
          kernel-branch: main
          config: vayu_user_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          python-27: true
          aosp-clang-version: r383902
          ksu: true
          release: true
          access-token: ${{ secrets.access_token }}
